export const CLOSE_MODAL = "CLOSE_MODAL";
export const FETCH_API = "FETCH_API";

export const FETCH_POKEMON_SUCCESS = "FETCH_POKEMON_SUCCESS";
export const FETCH_POKEMON_FAILED = "FETCH_POKEMON_FAILED";
export const FETCH_POKEMON_FROM_STORE = "FETCH_POKEMON_FROM_STORE";

export const SAVE_POKEMON_ID = "SAVE_POKEMON_ID";

export const SEARCH_POKEMON_SUCCESS = "SEARCH_POKEMON_SUCCESS";
export const SEARCH_POKEMON_FAILED = "SEARCH_POKEMON_FAILED";