export const FETCH_API = "FETCH_API";
export const FETCH_POKEMON_SUCCESS = "FETCH_POKEMON_SUCCESS";
export const FETCH_POKEMON_FAILED = "FETCH_POKEMON_FAILED";
export const SAVE_POKEMON_ID = "SAVE_POKEMON_ID";
export const SEARCH_POKEMON_BY_NAME = "SEARCH_POKEMON_BY_NAME";